/* generated no-op stubs -- symbols off the chunk-parser path */
__attribute__((weak)) long BPX4GGI() { return 0; }
__attribute__((weak)) long BPX4GGN() { return 0; }
__attribute__((weak)) long BPX4GPN() { return 0; }
__attribute__((weak)) long BPX4GPU() { return 0; }
__attribute__((weak)) long BPX4GUG() { return 0; }
__attribute__((weak)) long BPX4PWD() { return 0; }
__attribute__((weak)) long IRRSGS64() { return 0; }
__attribute__((weak)) long SAFEMLLC() { return 0; }
__attribute__((weak)) long SocketAddress_toString() { return 0; }
__attribute__((weak)) long directoryChangeModeRecursive() { return 0; }
__attribute__((weak)) long directoryClose() { return 0; }
__attribute__((weak)) long directoryCopy() { return 0; }
__attribute__((weak)) long directoryDeleteRecursive() { return 0; }
__attribute__((weak)) long directoryMake() { return 0; }
__attribute__((weak)) long directoryMakeDirectoryRecursive() { return 0; }
__attribute__((weak)) long directoryOpen() { return 0; }
__attribute__((weak)) long directoryRead() { return 0; }
__attribute__((weak)) long directoryRename() { return 0; }
__attribute__((weak)) long fileEOF() { return 0; }
__attribute__((weak)) long fileGetINode() { return 0; }
__attribute__((weak)) long fileUnixMode() { return 0; }
__attribute__((weak)) long getAddressByName2() { return 0; }
__attribute__((weak)) long getSocketDebugID() { return 0; }
__attribute__((weak)) long getUseridByCertificate() { return 0; }
__attribute__((weak)) long getUseridByDN() { return 0; }
__attribute__((weak)) long jwtAreBasicClaimsValid() { return 0; }
__attribute__((weak)) long jwtVerifyAndParseToken() { return 0; }
__attribute__((weak)) long loadCsi() { return 0; }
__attribute__((weak)) long makeJwtContextCustom() { return 0; }
__attribute__((weak)) long makeJwtContextForKeyInToken() { return 0; }
__attribute__((weak)) long makePipeBasedSyntheticSocket() { return 0; }
__attribute__((weak)) long returnEntries() { return 0; }
__attribute__((weak)) long symbolicFileInfo() { return 0; }
__attribute__((weak)) long timespec_to_ms() { return 0; }
